### ISSUE TITLE
Can't port forward containers when using Minikube

### ISSUE THREAD

**Issue by mikeroySoft** [vmware/octant#251]
When using Minikube, the option to port forward containers seems to be missing.
This seems to also offset the 'propagation' label.

"kubectl port-forward deployment/mike-nginx 7000:80" works just fine.

https://pasteboard.co/IwNnUf0.png

\>_ minikube version
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
\>_ octant version
Version:  0.6.0
Git commit:  a14f6a25a9d1cfa369652f0d237954122f680ca3
Built:  2019-08-28T09:21:29Z

\>_ kubectl get deployment mike-nginx -o yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 annotations:
   deployment.kubernetes.io/revision: "1"
 creationTimestamp: "2019-09-10T17:50:17Z"
 generation: 1
 labels:
   app: mike-nginx
 name: mike-nginx
 namespace: default
 resourceVersion: "864"
 selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/mike-nginx
 uid: 3c28b573-1908-4744-9180-12f1c9c222fd
spec:
 progressDeadlineSeconds: 600
 replicas: 1
 revisionHistoryLimit: 10
 selector:
   matchLabels:
     app: mike-nginx
 strategy:
   rollingUpdate:
     maxSurge: 25%
     maxUnavailable: 25%
   type: RollingUpdate
 template:
   metadata:
     creationTimestamp: null
     labels:
       app: mike-nginx
   spec:
     containers:
     \- image: nginx
       imagePullPolicy: Always
       name: nginx
       resources: {}
       terminationMessagePath: /dev/termination-log
       terminationMessagePolicy: File
     dnsPolicy: ClusterFirst
     restartPolicy: Always
     schedulerName: default-scheduler
     securityContext: {}
     terminationGracePeriodSeconds: 30
status:
 availableReplicas: 1
 conditions:
 \- lastTransitionTime: "2019-09-10T17:50:23Z"
   lastUpdateTime: "2019-09-10T17:50:23Z"
   message: Deployment has minimum availability.
   reason: MinimumReplicasAvailable
   status: "True"
   type: Available
\- lastTransitionTime: "2019-09-10T17:50:17Z"
   lastUpdateTime: "2019-09-10T17:50:23Z"
   message: ReplicaSet "mike-nginx-76785b796" has successfully progressed.
   reason: NewReplicaSetAvailable
   status: "True"
   type: Progressing
 observedGeneration: 1
 readyReplicas: 1
 replicas: 1
 updatedReplicas: 1

**Comment by GuessWhoSamFoo** [comment]
Octant currently looks for a container port. Per discussion with @bryanl about handling port forwarding on deployments, replicasets, and services, there needs to be some decisions made on how to track them and how this information should be displayed in `/cluster-overview/port-forward`

**Comment by bryanl** [comment]
@mikeroySoft Thanks for this. For Octant to know which port to forward, ports have to be available in the pod template spec. We don't have enough info to guess and still haven't figured out how to create port forwards to unknown ports in the GUI.

**Comment by bryanl** [comment]
I'm closing this issue as there isn't an action item. Not sure if Octant should try to guess about ports.

**Comment by mikeroySoft** [comment]
Looking back at this, I'm seeing the same behavior with `kind` when using `vctl` and VMware Fusion.
I'm wondering... is there something I can do to specify the available ports in the pod template spec?

**Comment by bryanl** [comment]
Yes. Here's an example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports: # container container an array of ports
        - containerPort: 80 # this field specifies the container port than Octant can see
```
