### ISSUE TITLE
Resource viewer loads forever for sidecar containers

### ISSUE THREAD

**Issue by GuessWhoSamFoo** [vmware/octant#83]
Example config:

```
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: sidecar
spec:
  selector:
    matchLabels:
      app: sidecar
  replicas: 2
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      volumes:
      - name: shared-logs 
        emptyDir: {}
    
      containers:
      - name: app-container
        image: alpine
        command: ["/bin/sh"]
        args: ["-c", "while true; do date >> /var/log/app.txt; sleep 5;done"]
    
        volumeMounts:
        - name: shared-logs
          mountPath: /var/log
    
      - name: sidecar-container
        image: nginx:1.16.0
        ports:
          - containerPort: 80
    
        volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/nginx/html
```
